Integrated Expression Language, updated tests, updated dependencies a…
php-etl/csv-plugin pull request #1
Opened 2021-05-26 14:29 UTC by sebprt

2021-06-01 06:39 UTC, gplanchat submitted a review, later dismissed

2021-06-01 06:39 UTC, gplanchat commented on src/Factory/Extractor.php
> +            columns: array_key_exists('columns', $config) ? $this->toAst($config['columns']) : null
cette méthode `toAst` ne pourrait pas être remplacée par la fonction `compileValue` ?

2021-06-01 06:39 UTC, gplanchat commented on src/Factory/Loader.php
>              columns: array_key_exists('columns', $config) ? $this->toAst($config['columns']) : null,
cette méthode `toAst` ne pourrait pas être remplacée par la fonction `compileValue` ?

2021-06-01 06:41 UTC, gplanchat requested changes
La méthode `toAst` devrait probablement être remplacée par la fonction `compileValue` ?

2021-06-01 07:31 UTC, sebprt commented on src/Factory/Extractor.php
> +            columns: array_key_exists('columns', $config) ? $this->toAst($config['columns']) : null
Effectivement c'est possible, c'est modifié

2021-06-01 07:31 UTC, sebprt commented on src/Factory/Loader.php
>              columns: array_key_exists('columns', $config) ? $this->toAst($config['columns']) : null,
Effectivement c'est possible, c'est modifié

2021-06-07 08:27 UTC, gplanchat approved these changes

2021-06-07 08:27 UTC, merged