Added the builder which allows to create several files
php-etl/csv-plugin pull request #3
Opened 2021-06-10 15:24 UTC by sebprt

2021-06-11 07:38 UTC, gplanchat requested changes

2021-06-11 07:38 UTC, gplanchat commented on src/Factory/Loader.php
> +        if (array_key_exists('line_number', $config)) {
Il faudrait vérifier que `$config['line_number']` soit supérieur ou égal à 1

2021-06-11 07:38 UTC, gplanchat commented on src/Configuration/Loader.php
> +                ->integerNode('line_number')
Est-ce que tu peux renommer ce paramètre en `max_lines` ?

2021-06-11 08:57 UTC, sebprt commented on src/Configuration/Loader.php
> +                ->integerNode('line_number')
C'est fait

2021-06-11 08:58 UTC, sebprt commented on src/Factory/Loader.php
> +        if (array_key_exists('line_number', $config)) {
Fait, au niveau de la configuration

2021-06-11 09:11 UTC, gplanchat approved these changes

2021-06-14 07:13 UTC, gplanchat approved these changes

2021-06-14 07:14 UTC, merged